# Generated by Django 3.2.5 on 2021-08-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userprofile_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onlineClass',
            field=models.ManyToManyField(blank=True, null=True, related_name='onlineClass', to='base.OnlineClass'),
        ),
    ]
