# Generated by Django 3.2.5 on 2021-08-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210804_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclass',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registerstudentforonlineclass',
            name='transId',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
