# Generated by Django 3.2.5 on 2021-08-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210806_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
