# Generated by Django 3.2.5 on 2021-08-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_onlineclass_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclass',
            name='hasOff',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
